
    player:
        normal up:
            - 6
            - 1
            - 1
        normal down:
            - 6
            - 2
            - 1
        normal left:
            - 6
            - 3
            - 1
        normal right:
            - 6
            - 4
            - 1
        special up:
            - 6
            - 5
            - 1
        special down:
            - 6
            - 6
            - 1
        special left:
            - 6
            - 7
            - 1
        special right:
            - 6
            - 8
            - 1
        shoot up:
            - 5
            - 9
            - 1
        shoot down:
            - 5
            - 10
            - 1
        shoot left:
            - 5
            - 11
            - 1
        shoot right:
            - 5
            - 12
            - 1
        walk up:
            - 8
            - 13
            - 0
        walk down:
            - 8
            - 14
            - 0
        walk left:
            - 8
            - 15
            - 0
        walk right:
            - 8
            - 16
            - 0
        idle up:
            - 5
            - 17
            - 0
        idle down:
            - 5
            - 18
            - 0
        idle left:
            - 5
            - 19
            - 0
        idle right:
            - 5
            - 20
            - 0
        hurt up:
            - 4
            - 21
            - 1
        hurt down:
            - 4
            - 22
            - 1
        hurt left:
            - 4
            - 23
            - 1
        hurt right:
            - 4
            - 24
            - 1
        interact up:
          - 5
          - 25
          - 1
        interact down:
          - 5
          - 26
          - 1
        interact left:
          - 5
          - 27
          - 1
        interact right:
          - 5
          - 28
          - 1
        charge up:
          - 6
          - 29
          - 0
        charge down:
          - 6
          - 30
          - 0
        charge left:
          - 6
          - 31
          - 0
        charge right:
          - 6
          - 32
          - 0
    enemy:
        idle:
            - 4
            - 33
            - 0
    coin:
        idle:
            - 6
            - 34
            - 0
    heart:
        idle:
            - 1
            - 35
            - 0
    bullet:
        up:
            - 1
            - 36
            - 0
        down:
            - 1
            - 37
            - 0
        left:
            - 1
            - 38
            - 0
        right:
            - 1
            - 39
            - 0
    gate:
      idle:
        - 5
        - 40
        - 0
    shopHeart:
        idle:
        - 1
        - 41
        - 0
    shopSpeed:
        idle:
        - 1
        - 42
        - 0
    hudCoin:
        - 1
        - 43
        - 0
    hudHeart:
        - 1
        - 44
        - 0
    boss:
      walk:
        - 10
        - 45
        - 1
      attack:
        - 10
        - 46
        - 1
      takeHit:
        - 10
        - 47
        - 1
      death:
        - 10
        - 48
        - 1
      idle:
        - 10
        - 49
        - 1
