
    player:
        attacking up:
            - 6
            - 1
        attacking down:
            - 6
            - 2
        attacking left:
            - 6
            - 3
        attacking right:
            - 6
            - 4
        attacking2 up:
            - 6
            - 5
        attacking2 down:
            - 6
            - 6
        attacking2 left:
            - 6
            - 7
        attacking2 right:
            - 6
            - 8
        attacking3 up:
            - 5
            - 9
        attacking3 down:
            - 5
            - 10
        attacking3 left:
            - 5
            - 11
        attacking3 right:
            - 5
            - 12
        walking up:
            - 8
            - 13
        walking down:
            - 6
            - 14
        walking left:
            - 6
            - 15
        walking right:
            - 6
            - 16
        idle up:
            - 5
            - 17
        idle down:
            - 5
            - 18
        idle left:
            - 5
            - 19
        idle right:
            - 5
            - 20
        hurt up:
            - 4
            - 21
        hurt down:
            - 4
            - 22
        hurt left:
            - 4
            - 23
        hurt right:
            - 4
            - 24
    enemy:
        idle:
            - 4
            - 25
    coin:
        idle:
            - 6
            - 26
    heart:
        idle:
            - 1
            - 27
    key:
        idle:
            - 1
            - 28
    chest:
        idle:
            - 2
            - 29
    bullet:
        up:
            - 1
            - 30
        down:
            - 1
            - 31
        left:
            - 1
            - 32
        right:
            - 1
            - 33
               
