
    player:
        normal up:
            - 6
            - 1
        normal down:
            - 6
            - 2
        normal left:
            - 6
            - 3
        normal right:
            - 6
            - 4
        special up:
            - 6
            - 5
        special down:
            - 6
            - 6
        special left:
            - 6
            - 7
        special right:
            - 6
            - 8
        shoot up:
            - 5
            - 9
        shoot down:
            - 5
            - 10
        shoot left:
            - 5
            - 11
        shoot right:
            - 5
            - 12
        walk up:
            - 8
            - 13
        walk down:
            - 8
            - 14
        walk left:
            - 8
            - 15
        walk right:
            - 8
            - 16
        idle up:
            - 5
            - 17
        idle down:
            - 5
            - 18
        idle left:
            - 5
            - 19
        idle right:
            - 5
            - 20
        hurt up:
            - 4
            - 21
        hurt down:
            - 4
            - 22
        hurt left:
            - 4
            - 23
        hurt right:
            - 4
            - 24
    enemy:
        idle:
            - 4
            - 25
    coin:
        idle:
            - 6
            - 26
    heart:
        idle:
            - 1
            - 27
    key:
        idle:
            - 1
            - 28
    chest:
        idle:
            - 2
            - 29
    bullet:
        up:
            - 1
            - 30
        down:
            - 1
            - 31
        left:
            - 1
            - 32
        right:
            - 1
            - 33
               
