name: CI
on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    if: contains(github.repository, 'sample-gradle-project') && !github.event.repository.fork
    strategy:
      matrix:
        os: [ windows-2022, macos-12, ubuntu-22.04 ]
        jvm_version: [17, 18, 19]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-build-${{ matrix.os }}-${{ matrix.jvm_version }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: DanySK/action-checkout@0.2.7
      - uses: DanySK/build-check-deploy-gradle-action@2.2.2
        with:
          custom-secret-0: ${{ secrets.OMDB_API_KEY }}
          java-version: ${{ matrix.jvm_version }}
          check-command: true
          deploy-command: |
            export OMDB_API_KEY="$CUSTOM_SECRET_0"
            ./gradlew check
          should-run-codecov: false
          should-deploy: true
          should-validate-wrapper: ${{ matrix.os == 'ubuntu' && matrix.jvm_version == '17' }}
  success:
    runs-on: ubuntu-22.04
    needs:
      - build
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
